### ISSUE TITLE
cattle-helm-system namespace job gets created in a loop

### ISSUE THREAD

**Issue by ronhorton** [aiyengar2/helm-project-operator#2]
this is in an rke2 ec2 downstream cluster

a. Click magnifying glass (search) in top menu
--
b. enter 'helm' in search field
c. select 'ProjectHemlCharts'
d. click Create from YAML
e. add name: demo
f. add namespace: cattle-project-p-ID from test-project namespace
g. add spec.helmapiversion: dummy.cattle.io/v1alpha1
h. click Create
i. Navigate to Workload > Jobs

expected: one job runs

actual result: job keeps getting created and added to the cattle-helm-namespace
<img width="1364" alt="Screen Shot 2022-04-21 at 3 41 32 PM" src="https://user-images.githubusercontent.com/89212856/164540161-8497809f-a149-4980-a42c-1d65c3ecec1a.png">

**Comment by aiyengar2** [comment]
Closed in favor of https://github.com/rancher/helm-project-operator/issues/5
